name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # You can configure fetch-depth as needed

      - name: Cache SonarCloud analysis results
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/sonarcloud_cache
          key: sonarcloud-analysis-${{ runner.os }}
          restore-keys: |
            sonarcloud-analysis-

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=santhosh80553
            -Dsonar.projectKey=mydockerrepo
