name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=santhosh80553
            -Dsonar.projectKey=mydockerrepo

      - name: Check SonarCloud Quality Gate
        run: |
          status=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=mydockerrepo" -H "Authorization: Basic $SONAR_TOKEN" | jq -r '.projectStatus.status')
          echo "SonarCloud Quality Gate Status: $status"

      - name: Calculate Percentage of Code Success
        id: code_success
        run: |
          if [ "$status" == "OK" ]; then
            echo "Percentage of Code Success: 100%"
          else
            echo "Percentage of Code Success: 0%"
          fi

      - name: Set Output Percentage
        run: echo "code_success_percentage=${{ steps.code_success.outputs.code_success }}" >> $GITHUB_ENV

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
