name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache SonarCloud analysis
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonarcloud-${{ runner.os }}-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            sonarcloud-${{ runner.os }}-
            sonarcloud-

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=santhosh80553
            -Dsonar.projectKey=mydockerrepo
        # ... (other SonarCloud arguments)

      - name: Extract SonarCloud analysis data
        id: sonarcloud-data
        run: |
          echo "SonarCloud Analysis ID: ${{ steps.DemoSonarCloudScan.outputs.sonar_analysis_id }}"
          echo "SonarCloud Quality Gate Status: ${{ steps.DemoSonarCloudScan.outputs.sonar_quality_gate_status }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
