name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Explicitly specify node16

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov selenium playwright

      - name: Running pytest
        run: |
          pytest -v  --cov --cov-report=xml --cov-report=html

      - name: Analysing the code with pylint
        continue-on-error: true
        run: |
          pylint src/git_graph_automation

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=santhosh80553
            -Dsonar.projectKey=mydockerrepo
